### ISSUE TITLE
Monster Lab Notebook

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/OA_variability#13]
I wanted to save the master (monster) lab notebook for oceans variability stuff. It's sort of overwhelming but it can be a useful reference.  Not all of the figures are that useful, interesting or all that clear. 

I will print out the more interesting figures for meetings. 

When it says ` ## NULL`  it means there is figure missing because CMIP or the observational data sets are missing a variable.

**Comment by cahartin** [comment]
maybe we can make multiple lab notebooks? based on variable?

**Comment by kdorheim** [comment]
Arg it's too big to GitHub's unhappy

**Comment by cahartin** [comment]
i'm not surprised! ha!
